src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Code;
use AppBundle\Entity\Comments;
use AppBundle\Form\commentType;
use AppBundle\Form\snippetType;
use AppBundle\Services\PaginationService;
use FOS\UserBundle\Controller\SecurityController as BaseController;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends BaseController
{
    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->container->get('security.token_storage')->getToken()->getUser();
    }

    /**
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function mySnippetsAction($page = 1)
    {
        $results = $this->getDoctrine()
            ->getManager()
            ->getRepository('AppBundle:Code')
            ->getResultsForPagination($this->getUser());

        $pages = PaginationService::getPagesCount($results);
        $content = PaginationService::paginate($results, 10, $page);

        return $this->render('AppBundle:default:my-snippets.html.twig', array(
            'results' => $content,
            'page' => $page,
            'pages' => $pages
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function newSnippetAction(Request $request, $page = 1)
    {
        $entity = new Code();

        $form = $this->createForm(snippetType::class, $entity, array('method' => 'POST'));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            $results = $this->getDoctrine()
                ->getManager()
                ->getRepository('AppBundle:Code')
                ->getResultsForPagination($this->getUser());

            $pages = PaginationService::getPagesCount($results);
            $content = PaginationService::paginate($results, 10, $page);

            return $this->render('AppBundle:default:my-snippets.html.twig', array(
                'results' => $content,
                'page' => $page,
                'pages' => $pages
            ));
        }


        return $this->render('AppBundle:default:new-snippet.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @param int $id
     * @param Request $request
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function snippetDetailsAction($id = 1, Request $request, $page = 1)
    {
        $entity = new Comments();

        $form = $this->createForm(commentType::class, $entity, array('method' => 'POST'));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();
        }

        $own = $this
                    ->getDoctrine()
                    ->getRepository('AppBundle:Code')
                    ->getOneResultByUser($id, $this->getUser());

        $public = $this
                    ->getDoctrine()
                    ->getRepository('AppBundle:Code')
                    ->getOneResultByPublic($id);

        $comments = $this
                    ->getDoctrine()
                    ->getRepository('AppBundle:Comments')
                    ->getCommentsById($id);

        if(!$own && !$public){
            return $this->render('TwigBundle:Exception:error404.html.twig',array());
        }

        return $this->render('AppBundle:default:snippet-details.html.twig', array(
            'result' => $public ?: $own,
            'comments' => $comments,
            'form' => $form->createView(),
        ));
    }

    /**
     * @param int $id
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function deleteSnippetAction($id = 1, $page = 1)
    {
        $em = $this
                    ->getDoctrine()
                    ->getEntityManager();

        $item = $em
                    ->getRepository('AppBundle:Code')
                    ->getOneResultByUser($id, $this->getUser());

        $em->remove($item);
        $em->flush();

        $results = $this
                    ->getDoctrine()
                    ->getManager()
                    ->getRepository('AppBundle:Code')
                    ->getResultsForPagination($this->getUser());

        $pages = PaginationService::getPagesCount($results);
        $content = PaginationService::paginate($results, 10, $page);

        return $this->render('AppBundle:default:my-snippets.html.twig', array(
            'results' => $content,
            'page' => $page,
            'pages' => $pages
        ));
    }

    /**
     * @param Request $request
     * @param int $id
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     *
     */
    public function editSnippetAction(Request $request, $id = 1, $page = 1)
    {
        $edit = $this->getDoctrine()
            ->getRepository('AppBundle:Code')
            ->find($id);

        $form = $this->createForm(snippetType::class, $edit);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($edit);
            $em->flush();

            $results = $this->getDoctrine()
                    ->getManager()
                    ->getRepository('AppBundle:Code')
                    ->getResultsForPagination($this->getUser());

            $pages = PaginationService::getPagesCount($results);
            $content = PaginationService::paginate($results, 10, $page);

            return $this->render('AppBundle:default:my-snippets.html.twig', array(
                'results' => $content,
                'page' => $page,
                'pages' => $pages
            ));
        }

        return $this->render('AppBundle:default:edit-snippet.html.twig',array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function searchSnippetAction(Request $request)
    {
        $term  = $request->get('term');

        $own   = $this
                    ->getDoctrine()
                    ->getManager()
                    ->getRepository('AppBundle:Code')
                    ->getSearchResults($term, $this->getUser());

        $public = $this
                    ->getDoctrine()
                    ->getManager()
                    ->getRepository('AppBundle:Code')
                    ->getPublicResults($term, $this->getUser());

        return $this->render('AppBundle:default:search-page.html.twig', array(
            'results' => array_merge($own, $public)
        ));
    }
}

src/AppBundle/Resources/views/default/comments.html.twig
<div class="row">
    <div class="col-md-12">
        {% if comments %}
            {% for comment in comments %}
                <b>{{ comment.user|lower|capitalize }} {{ 'comment.date'|trans([], "frontend") }} {{ comment.createdAt|date('d.m.Y') }} {{ 'comment.at'|trans([], "frontend") }} {{ comment.createdAt|date('H:i') }} {{ 'comment.clock'|trans([], "frontend") }}:</b>
                {{ comment.message|raw }}
                <br>
            {% endfor %}
        {% endif %}
    </div>
</div>

src/AppBundle/Resources/views/default/edit-snippet.html.twig
{% trans_default_domain 'AppBundle' %}

{% extends 'base.html.twig' %}

{% block contentHeadline %} {{ 'snippets.edit'|trans({},'frontend') }}{% endblock %}
{#{% block contentSubHeadline %}{% endblock %}#}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <button class="btn btn-primary btn-position-left" onclick="history.back();">{{ 'form.prev'|trans([],'forms') }}</button>
            {{ form_start(form) }}
            <div class="form-group">
                {{ form_row(form.user) }}
                {{ form_row(form.language) }}
                <br>
                {{ form_row(form.description) }}
            </div>
            <div class="form-group">
                {{ form_row(form.snippet) }}
            </div>
            <div class="form-group">
                {{ form_row(form.information) }}
            </div>
            <div class="form-group">
                {{ form_row(form.public) }}
            </div>
            <input type="submit" class="btn btn-primary btn-position-right" value="{{ 'form.save'|trans({},'forms') }}">
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block javascript %}{% endblock %}

src/AppBundle/Resources/views/default/my-snippets.html.twig
{% trans_default_domain 'AdminBundle' %}

{% extends 'base.html.twig' %}

{% block contentHeadline %} {{ 'snippets.my_snippets'|trans([], 'frontend') }}{% endblock %}
{#{% block contentSubHeadline %}{% endblock %}#}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <th>{{ 'language'|trans([], 'frontend') }}</th>
                <th>{{ 'description'|trans([], 'frontend') }}</th>
                <th></th>
                <th></th>
                </thead>
                <tbody>
                {% for result in results %}
                    <tr>
                        <td><a href="{{ path('snippet_details') }}/{{ result.id }}" target="_self">{{ result.language }}</a></td>
                        <td><a href="{{ path('snippet_details') }}/{{ result.id }}" target="_self">{{ result.description }}</a></td>
                        <td>
                            {% if result.public == false  %}
                                <span class="label label-sm label-warning">{{ 'public.false'|trans({}, 'forms') }}</span>
                            {% else %}
                                <span class="label label-sm label-success">{{ 'public.true'|trans({}, 'forms') }}</span>
                            {% endif %}
                        </td>
                        <td>
                            <div class="btn-group">
                                <button class="btn btn-xs btn-success">
                                    <a href="{{ path('snippet_details') }}/{{ result.id }}" target="_self" class="">
                                        <i class="ace-icon fa fa-check bigger-120" style="color:white;"></i>
                                    </a>
                                </button>

                                <button class="btn btn-xs btn-info">
                                    <a href="{{ path('edit_snippet') }}/{{ result.id }}" target="_self" class="">
                                        <i class="ace-icon fa fa-pencil bigger-120" style="color:white;"></i>
                                    </a>
                                </button>

                                <button class="btn btn-xs btn-danger">
                                    <a href="{{ path('delete_snippet') }}/{{ result.id }}" target="_self" class="">
                                        <i class="ace-icon fa fa-trash-o bigger-120" style="color:white;"></i>
                                    </a>
                                </button>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {% if pages > 1 %}
                <div class="row">
                    <div class="col-lg-12">
                        {% include 'AppBundle:default:pagination.html.twig' with {
                        'route': 'list_page',
                        'parameters': {},
                        'page': page,
                        'pages': pages,
                        } %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascript %}{% endblock %}

src/AppBundle/Resources/views/default/new-comment.html.twig
<div class="row">
    <div class="col-md-12">
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_row(form.user) }}
            {{ form_widget(form.code_id, {'value' : app.request.get('id')}) }}
            {{ form_row(form.message) }}
        </div>
        <input type="submit" class="btn btn-primary btn-position-right" value="{{ 'form.save'|trans({},'forms') }}">
        {{ form_end(form) }}
    </div>
</div>

src/AppBundle/Resources/views/default/new-snippet.html.twig
{% trans_default_domain 'AppBundle' %}

{% extends 'base.html.twig' %}

{% block contentHeadline %} {{ 'snippets.new_snippets'|trans([], 'frontend') }}{% endblock %}
{#{% block contentSubHeadline %}{% endblock %}#}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {{ form_start(form) }}
                <div class="form-group">
                    {{ form_row(form.user) }}
                    {{ form_row(form.language) }}
                    <br>
                    {{ form_row(form.description) }}
                </div>
                <div class="form-group">
                    {{ form_row(form.snippet) }}
                </div>
                <div class="form-group">
                    {{ form_row(form.information) }}
                </div>
                <div class="form-group">
                    {{ form_row(form.public) }}
                </div>
                <input type="submit" class="btn btn-primary btn-position-right" value="{{ 'form.save'|trans({},'forms') }}">
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block javascript %}{% endblock %}

src/AppBundle/Resources/views/default/pagination.html.twig
{% set parameters = parameters is defined ? parameters : {} %}
{% set first_parameters = parameters|merge({'page': 1 }) %}
{% set prev_parameters = parameters|merge({'page': page - 1}) %}
{% set next_parameters = parameters|merge({'page': page + 1}) %}
{% set last_parameters = parameters|merge({'page': pages }) %}

{% set additional = 5 %}

{% set start_page = max(1, page - additional) %}
{% set end_page = min(pages, page + additional) %}

{% set delta = end_page - start_page - additional %}
{% set end_page = min(pages, end_page + ( delta <= additional ? additional - delta : 0)) %}
{% set start_page = max(1, start_page - ( delta <= additional ? additional - delta : 0)) %}

<nav aria-label="Page navigation">
    <ul class="pagination">
        {%  set class = page <= 1 ? 'disabled' : '' %}
        <li class="{{ class }}">
            <a href="{{ path(route, first_parameters) }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {%  set class = page <= 1 ? 'disabled' : '' %}
        <li class="{{ class }}">
            <a href="{{ path(route, prev_parameters) }}" aria-label="Previous">
                <span aria-hidden="true">&lsaquo;</span>
            </a>
        </li>

        {% for x in start_page..end_page %}
            {% set current_parameters = parameters|merge({'page': x }) %}
            {% set class = page == x ? 'active' : '' %}
            <li class="{{ class }}"><a href="{{ path(route, current_parameters) }}">{{ x }}</a></li>
        {% endfor %}

        {%  set class = page >= pages ? 'disabled' : '' %}
        <li class="{{ class }}">
            <a href="{{ path(route, next_parameters) }}" aria-label="Next">
                <span aria-hidden="true">&rsaquo;</span>
            </a>
        </li>
        <li class="{{ class }}">
            <a href="{{ path(route, last_parameters) }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

src/AppBundle/Resources/views/default/search-page.html.twig
{% trans_default_domain 'AppBundle' %}

{% extends 'base.html.twig' %}

{% block contentHeadline %} {{ 'page.search'|trans([], 'frontend') }}{% endblock %}
{#{% block contentSubHeadline %}{% endblock %}#}

{% block content %}
    {% set user = app.user.username %}
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <th>{{ 'language'|trans([], 'frontend') }}</th>
                <th>{{ 'description'|trans([], 'frontend') }}</th>
                <th></th>
                <th></th>
                </thead>
                <tbody>
                {% for result in results %}
                    <tr>
                        <td><a href="{{ path('snippet_details') }}/{{ result.id }}" target="_self">{{ result.language }}</a></td>
                        <td><a href="{{ path('snippet_details') }}/{{ result.id }}" target="_self">{{ result.description }}</a></td>
                        <td>
                            {% if result.public == false  %}
                                <span class="label label-sm label-warning">{{ 'public.false'|trans({}, 'forms') }}</span>
                            {% else %}
                                <span class="label label-sm label-success">{{ 'public.true'|trans({}, 'forms') }}</span>
                            {% endif %}

                            {% if result.user == user %}
                                <span class="label label-sm label-inverse">{{ 'public.own'|trans({}, 'forms') }}</span>
                            {% else %}
                                <span class="label label-sm label-info">{{ result.user }}</span>
                            {% endif %}
                        </td>
                        <td>
                            <div class="btn-group">
                                <button class="btn btn-xs btn-success">
                                    <a href="{{ path('snippet_details') }}/{{ result.id }}" target="_self" class="">
                                        <i class="ace-icon fa fa-check bigger-120" style="color:white;"></i>
                                    </a>
                                </button>

                                {% if result.user == user %}
                                    <button class="btn btn-xs btn-info">
                                        <a href="{{ path('edit_snippet') }}/{{ result.id }}" target="_self" class="">
                                            <i class="ace-icon fa fa-pencil bigger-120" style="color:white;"></i>
                                        </a>
                                    </button>

                                    <button class="btn btn-xs btn-danger">
                                        <a href="{{ path('delete_snippet') }}/{{ result.id }}" target="_self" class="">
                                            <i class="ace-icon fa fa-trash-o bigger-120" style="color:white;"></i>
                                        </a>
                                    </button>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block javascript %}{% endblock %}

src/AppBundle/Resources/views/default/snippet-details.html.twig
{% trans_default_domain 'AppBundle' %}

{% extends 'base.html.twig' %}

{% block contentHeadline %} {{ 'snippets.details'|trans({},'frontend') }}{% endblock %}
{#{% block contentSubHeadline %}{% endblock %}#}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <button class="btn btn-primary btn-position-left" onclick="history.back();">{{ 'form.prev'|trans([],'forms') }}</button>

            {% set user = app.user.username %}
            {% if result.user == user %}
                <a href="{{ path('edit_snippet') }}/{{ result.id }}" class="btn  btn-position-left">{{ 'form.edit'|trans([],'forms') }}</a>
            {% endif %}

            <div class="snippet-details-header">
                <b>{{ result.description|raw }}</b>
            </div>
            <div class="snippet-details-body">
                <pre>
                    <code class="language-{{ result.language }}">
                        {{ result.snippet|striptags|raw}}
                    </code>
                </pre>
            </div>
            <div class="snippet-details-footer">
                {{ result.information|raw }}

                <table class="table table-striped margin-top">
                    <tr>
                        <td>{{ 'public.creator'|trans([], 'frontend') }}: </td>
                        <td>{{ result.user|lower|capitalize }}</td>
                    </tr>
                    <tr>
                        <td>{{ 'public.language'|trans([], 'frontend') }}: </td>
                        <td>{{ result.language }}</td>
                    </tr>
                    <tr>
                        <td>{{ 'public.createdAt'|trans([], 'frontend') }}:</td>
                        <td>{{ result.createdAt|date('d.m.Y') }}</td>
                    </tr>
                    <tr>
                        <td>{{ 'public.modifiedAt'|trans([], 'frontend') }}: </td>
                        <td>{{ result.modifiedAt|date('d.m.Y') }}</td>
                    </tr>
                    <tr>
                        <td>{{ 'public.visible'|trans([], 'frontend') }}:</td>
                        <td>{{ result.public == '1' ? 'public.true'|trans([], 'frontend')  :  'public.false'|trans([], 'frontend')  }}</td>
                    </tr>
                </table>
            </div>

            {% if result.public == '1' %}
                <div class="snippet-details-comments">
                    <div class="margin-top">
                        {{ include('@App/default/comments.html.twig') }}
                    </div>
                    <div class="margin-top">
                        {{ include('@App/default/new-comment.html.twig') }}
                    </div>
                </div>
            {% endif %}

        </div>
    </div>
{% endblock %}

{% block javascript %}{% endblock %}